channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost>=2.1.0,<4.0.0
name: mlflow-env