name: stroke-prediction-mlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow>=2.0.0
    - scikit-learn>=1.3.0
    - pandas>=1.5.0
    - numpy>=1.24.0
    - xgboost>=1.7.0
    - matplotlib>=3.6.0
    - seaborn>=0.12.0