name: stroke-prediction-mlproject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - mlflow==3.1.0
    - scikit-learn==1.7.0
    - pandas==2.3.0
    - numpy==2.3.0
    - xgboost==3.0.2
    - matplotlib==3.10.3
    - seaborn==0.13.2